export const fakeData = [
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
  {
    partId: '123',
    name: 'GammaBlaster',
    modelNumber: 'FdD322',
    supplier: 'Suno Ranjan',
    manufacturer: 'Stark Industry',
    price: '1M',
    location: 'Godown',
  },
];
